title: Your Academic Website
description: Personal academic website
baseurl: ""
url: ""

# Build settings
markdown: kramdown
encoding: utf-8

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass
sass:
  style: compressed
  sass_dir: _sass

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .gitignore
  - README.md
